### ISSUE TITLE
Cannot launch FlatFab on Ubuntu

### ISSUE THREAD

**Issue by hellocatfood** [JamesMcCrae/flatfab#1]
I'm attempting to run FlatFab on Ubuntu 18.10 but when I run ./FlatFab I get the following error:

`/FlatFab: error while loading shared libraries: libgstreamer-0.10.so.0: cannot open shared object file: No such file or directory`

I think this is because gstreamer has been updated since previous versions of Ubuntu. Can FlatFab be compiled to use the latest version on gstreamer?

**Comment by zfmaster** [comment]
@hellocatfood did you got any success in this? On 20.04 it's, of course, also not running and there is no chance to make it work with libgstreamer-1.0 without updating source code.

@JamesMcCrae, @depaolic, Could you help with compiling instructions? It would be god to have possibility to modify sources if it's anyway open source.

**Comment by hellocatfood** [comment]
@zfmaster Couldn't get it running unfortunately. I see there was a commit to this repository in 2009 but that was only to the README so I'd say this project is pretty much abandoned

**Comment by zfmaster** [comment]
@hellocatfood Actually I was able to compile it for Ubuntu relatively easy after some research: it uses nothing but standard QT 5 functionality, so the key is to install QT 5, add missing modules (webkit), add Eigen and after that configure it with qmake and compile with make. That's all. 
BTW: I'm thinking about making fork of it and extending readme in beginning with idea to extend the tool with new functionalities. Would be good to have bigger community for it.

**Comment by hellocatfood** [comment]
@zfmaster oh wow, that's great to hear! Yes, please do fork it and extend the readme and add new functionalities!

**Comment by skadge** [comment]
@hellocatfood @zfmaster -> cf #9

**Comment by JamesMcCrae** [comment]
Excellent @skadge !  Closing this issue.
