### ISSUE TITLE
allow creating shapes below z=0 plane

### ISSUE THREAD

**Issue by skadge** [JamesMcCrae/flatfab#11]
It seems it is currently not possible to create a shape below the z=0 plane (all points are clamped to z=0).

This is a bit annoying when starting sketching a model from a template image, as the template image is not always above z=0:

![image](https://github.com/user-attachments/assets/e9a14c09-8390-47ba-89c3-0fb9644a6848)

**Comment by JamesMcCrae** [comment]
Fixed via 0340ed3526f702b543f8f0878f3a7bf17216824a

In the application Edit menu, there is a new checkbox at the bottom "Clip to Ground Plane" which can be used to enable/disable this as needed.

![image](https://github.com/user-attachments/assets/9426e642-dd22-4606-ab0b-74690789b0c8)
