### ISSUE TITLE
use standardf keyboard/mouse shortcuts for 3D navigation

### ISSUE THREAD

**Issue by skadge** [JamesMcCrae/flatfab#12]
While there is not general consensus on mouse/keyboard shortcuts in 2D/3D creative apps, FlatFab uses especially unusual shortcuts for 3D navigation and interactions, which makes the usage of the application a bit unintuitve:

FlatFab:

- pan: Shift + left click
- 3D rotation: Left click (in empty area)
- zoom: ctrl + left click
- vertex selection: right click

Inkscape:
- pan: middle click
- 3D rotation: N/A
- zoom: ctrl + middle click
- selection: left click

Gimp:
- pan: middle click
- 3D rotation: N/A
- zoom: ctrl + middle click
- selection: left click

PrusaSlicer:
- pan: middle click/right click
- 3D rotation: Left click (in empty area)
- zoom: mouse wheel
- vertex selection: right click

Blender:
- pan: shift + middle click
- 3D rotation: middle click
- zoom: mouse wheel/ctrl + middle click
- selection: left click

LightBurn:
- pan: middle click
- 3D rotation: N/A
- zoom: mouse wheel
- selection: left click

So, based on existing tools, I would for instance suggest:

- pan: **Middle click**
- 3D rotation: **Left click (in empty area)**
- zoom: **mouse wheel/ctrl + middle click**
- vertex selection: **left click**

What do you think?

**Comment by JamesMcCrae** [comment]
Addressed (mostly) for pan, 3D rotation and zoom via f4e0a84f794a651658ab433f249bb1a798a45e4b, vertex selection/editing will require some additional thought (as left click may cause some accidental interactions if the vertex is missed).
