### ISSUE TITLE
Does not work on windows 10 pro 

### ISSUE THREAD

**Issue by OnionBoots** [JamesMcCrae/flatfab#3]
unzipped after downloading from official website , running the main exe file , a small window appears with title Flatfab 0.8.0 beta
with rest things in white color then the app crashes

**Comment by JamesMcCrae** [comment]
Very late in response, but I recently tested the version hosted on http://flatfab.com specifically on a workstation with Windows 10 Pro 64-bit installed, and the application did work as expected without crashing.  So there may have been something unique with your configuration.  Closing the issue.
